services:
  postgres:
    image: 'postgres:16'
    environment:
      - 'POSTGRES_DB=oauth2'
      - 'POSTGRES_PASSWORD=${POSTGRES_PASSWORD}'
      - 'POSTGRES_USER=${POSTGRES_USER}'
    ports:
      - '${POSTGRES_PORT}:5432'
