spring:
  application:
    name: backend
  flyway:
    placeholders:
      ADMIN_USERNAME: ${ADMIN_USERNAME}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}

      REGULAR_USER_USERNAME: ${REGULAR_USER_USERNAME}
      REGULAR_USER_PASSWORD: ${REGULAR_USER_PASSWORD}