spring:
  application:
    name: backend
  flyway:
    placeholders:
      ADMIN_USERNAME: ${ADMIN_USERNAME}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}

      REGULAR_USER_USERNAME: ${REGULAR_USER_USERNAME}
      REGULAR_USER_PASSWORD: ${REGULAR_USER_PASSWORD}
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
            scope:
              - read:user
              - user:email
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile
security:
  token:
    expiration: ${JWT_EXPIRATION_SECONDS}
    refresh-expiration: ${JWT_REFRESH_EXPIRATION_SECONDS}
    secret: ${JWT_SECRET}
    issuer: ${JWT_ISSUER}